#!/bin/bash
set -euo pipefail

if ! localectl set-x11-keymap us_da '' '' 'compose:menu,caps:escape'; then
	echo "Couldn't set us_da keymap!"
fi

# Install vim-plug for neovim
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
nvim +PlugInstall

# Install fundle for fish
curl -fLo ~/.config/fish/functions/fundle.fish --create-dirs https://git.io/fundle
fish -c 'fundle install'
